*  ===============================================
*  = First select those sites in the workin data =
*  ===============================================
use ../data/working.dta, clear
contract icode, freq(v)
label var v "visit count"
merge 1:1 icode using ../data/sites.dta
keep if _m == 3
drop _m



* ===========================
* = Characteristics by site =
* ===========================

* example text at bottomr
* depends on sites_ordered_by_visits which is generated by an_visits_by_month

use ../data/working.dta, clear
count
contract icode dorisname v_ccmds
merge m:1 icode using ../data/sites_ordered_by_visits
sort order
rename _freq v
drop _m
drop if v_ccmds==.
reshape wide v, i(icode) j(v_ccmds)
rename v* ccmds*
forvalues i=0/3 {
replace ccmds`i'=0 if ccmds`i'==.
}
order dorisname ccmds*
sort order
egen v_total=rowtotal(ccmds*)
forvalues i=0/3 {
replace ccmds`i'=round(ccmds`i'/v_total*100) 
}


exit

results generated 120926

ccmds0+ccmds1+ccmds2+ccmds3

41+50+9+0
8+89+3+0
16+61+21+3
1+85+14+0
1+77+21+1
2+82+15+0
0+86+10+3
0+23+74+4
6+52+36+6
10+85+5+0
31+60+7+1
4+77+17+1
2+55+40+3
4+76+19+1
1+92+6+0
3+73+24+0
38+57+5+0
62+38+0+0
23+25+51+0
20+69+11+0
23+70+7+0
19+72+5+3
13+84+3+0
0+57+41+1
2+93+5+0
19+42+38+1
1+40+46+13
9+46+43+2
92+8+0+0
2+71+25+3
1+70+21+8
0+36+64+0
1+36+61+2
1+50+48+1
15+78+6+1
4+68+24+4
41+44+13+2
64+35+0+1
12+86+2+1
82+16+2+0

*  ===============================
*  = Treatment limitation orders =
*  ===============================
use ../data/working.dta, clear
gen rxlimits=inlist(v_disposal,4,7)
collapse (mean) rxlimits (firstnm) dorisname, by(icode)
replace rxlimits=round(rxlimits*100)
merge 1:1 icode using ../data/sites_ordered_by_visits
drop _m
sort order

exit
results as of 26 Sep 2012

rxlimits
23
19
15
11
19
18
10
28
7
17
6
9
16
15
28
8
18
8
9
15
12
6
22
9
7
6
3
6
9
9
15
17
15
18
11
13
13
14
14
2

*  =========================================
*  = ICNARC acute physiology score by site =
*  =========================================
use ../data/working.dta, clear
su icnarc_score
hist icnarc_score, s(1) w(1) freq
graph export ../logs/icnarc_score.pdf, replace
egen icnarc_s10 = cut(icnarc_score), at(0(5)45,100)
tab icnarc_s10
contract icode icnarc_s10, freq(v)
reshape wide v, i(icode) j(icnarc_s10)
forvalues i=0(5)45 {
replace v`i'=0 if v`i'==.
}
rename v* icnarc*
merge 1:1 icode using ../data/sites_ordered_by_visits
drop _m
sort order
egen v_total=rowtotal(icnarc*)
forvalues i=0(5)45 {
replace icnarc`i'=round(icnarc`i'/v_total*100)
}

exit

data generated using above code 26 Sep 2012

icode	icnarc0	icnarc5	icnarc10	icnarc15	icnarc20	icnarc25	icnarc30	icnarc35	icnarc40	icnarc45	order	v_total
52s	6	26	29	19	13	5	1	1	0	0	1	1428
13s	10	37	30	16	6	2	0	0	0	0	2	993
03s	6	21	26	21	13	9	2	1	1	0	3	689
67s	2	12	23	30	19	10	3	0	0	0	4	605
59s	4	21	25	24	13	9	4	0	1	0	5	669
94s	1	12	32	28	18	6	2	1	0	0	6	473
21s	2	10	21	25	20	13	6	3	0	0	7	534
07s	7	19	31	21	13	6	2	0	1	0	8	482
25s	3	16	28	27	16	6	2	1	0	0	9	442
38s	4	19	33	21	13	8	1	1	0	0	10	378
89s	5	21	30	20	13	6	2	1	0	0	11	321
83s	1	8	22	27	22	15	4	0	1	1	12	310
41s	4	16	24	22	16	12	3	1	0	0	13	313
11s	2	15	27	23	20	8	2	2	0	0	14	422
17s	10	28	25	18	9	6	3	1	0	0	15	300
24s	5	16	21	20	21	10	5	2	1	0	16	301
79s	2	11	26	26	19	9	5	1	1	0	17	243
30s	1	12	21	28	21	14	2	0	0	0	18	222
23s	3	18	24	27	21	5	1	0	0	0	19	251
05s	2	12	27	27	16	11	5	0	0	0	20	233
57s	1	9	23	24	23	14	3	2	1	0	21	285
87s	1	14	22	24	19	12	6	2	1	0	22	232
29s	5	18	25	25	13	10	4	1	0	0	23	309
55s	2	15	22	24	18	10	6	2	1	0	24	188
69s	5	25	19	26	14	8	2	0	0	0	25	259
84s	2	13	25	17	24	14	4	1	2	0	26	193
63s	5	13	14	19	23	13	6	5	1	1	27	154
48s	1	5	22	23	28	17	2	2	0	0	28	87
09s	6	16	23	25	18	11	1	1	0	0	29	125
86s	6	20	24	21	17	11	3	1	0	0	30	200
85s	10	18	22	20	15	9	5	0	0	0	31	401
71s	0	3	22	27	21	14	6	8	0	0	32	78
27s	5	12	26	25	15	12	5	0	1	0	33	155
98s	4	20	27	27	12	5	2	1	0	0	34	157
65s	4	20	26	25	15	8	3	1	0	0	35	171
34s	5	22	30	21	15	4	1	2	0	0	36	162
33s	8	32	21	22	10	4	2	1	0	0	37	157
53s	1	11	19	30	22	10	4	1	1	0	38	73
49s	3	14	30	21	17	12	2	1	0	0	39	185
81s	1	17	33	26	14	6	2	1	0	0	40	361

icnarc0	icnarc5	icnarc10	icnarc15	icnarc20	icnarc25	icnarc30	icnarc35	icnarc40	icnarc45

6+26+29+19+13+5+1+1+0+0
10+37+30+16+6+2+0+0+0+0
6+21+26+21+13+9+2+1+1+0
2+12+23+30+19+10+3+0+0+0
4+21+25+24+13+9+4+0+1+0
1+12+32+28+18+6+2+1+0+0
2+10+21+25+20+13+6+3+0+0
7+19+31+21+13+6+2+0+1+0
3+16+28+27+16+6+2+1+0+0
4+19+33+21+13+8+1+1+0+0
5+21+30+20+13+6+2+1+0+0
1+8+22+27+22+15+4+0+1+1
4+16+24+22+16+12+3+1+0+0
2+15+27+23+20+8+2+2+0+0
10+28+25+18+9+6+3+1+0+0
5+16+21+20+21+10+5+2+1+0
2+11+26+26+19+9+5+1+1+0
1+12+21+28+21+14+2+0+0+0
3+18+24+27+21+5+1+0+0+0
2+12+27+27+16+11+5+0+0+0
1+9+23+24+23+14+3+2+1+0
1+14+22+24+19+12+6+2+1+0
5+18+25+25+13+10+4+1+0+0
2+15+22+24+18+10+6+2+1+0
5+25+19+26+14+8+2+0+0+0
2+13+25+17+24+14+4+1+2+0
5+13+14+19+23+13+6+5+1+1
1+5+22+23+28+17+2+2+0+0
6+16+23+25+18+11+1+1+0+0
6+20+24+21+17+11+3+1+0+0
10+18+22+20+15+9+5+0+0+0
0+3+22+27+21+14+6+8+0+0
5+12+26+25+15+12+5+0+1+0
4+20+27+27+12+5+2+1+0+0
4+20+26+25+15+8+3+1+0+0
5+22+30+21+15+4+1+2+0+0
8+32+21+22+10+4+2+1+0+0
1+11+19+30+22+10+4+1+1+0
3+14+30+21+17+12+2+1+0+0
1+17+33+26+14+6+2+1+0+0
